### ISSUE TITLE
File not found as wheel: pymclevel-0.1.

### ISSUE THREAD

**Issue by Kaixhin** [aigamedev/pmgai-minecraft#1]
I've run `nuclai install minecraft` inside my pmgai directory with virtualenv, but I get the error `File not found as wheel: pymclevel-0.1.`. I'm a Python novice, so I tried running `pip install` on the various wheel files on the [releases page](https://github.com/aigamedev/pymclevel/releases), but kept getting an error saying that my platform was not supported (I'm running OS X 10.9.5). Finally I used `pip install` on the .tar.gz release file after installing all of pymclevel's dependencies manually. But `nuclai install minecraft` of course still fails.

I'm having varying success trying to install everything else manually, so a little more clarity here would be appreciated.

**Comment by alexjc** [comment]
There's only one wheel that could work (the OSX one) and it seems like it has 10.10 in the filename. Maybe try renaming the filename?

Otherwise you'll just have to install from source with `python3.4 setup.py install` as usual from the Git checkout.

**Comment by Kaixhin** [comment]
Yep it looks like just downloading the wheel and renaming it with `10_9` seems to work fine - if you can just add the wheels for `10_8`, `10_9` and `10_11` then it'll probably work fine and you can close this issue.

Now I'm trying to install pymcworldgen using a `pip install` on the GitHub .zip of master (which is the commit specified in `nuclai.json`), and I get the following stack trace - any ideas?

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
      File "/Users/kai/Projects/pmgai/env/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/fc/26klnndd3n11999fmhp84qn00000gn/T/pip-3c2semk3-build/setup.py'
```

**Comment by alexjc** [comment]
It may be a problem with sudo? Normally I `git clone` then run `python3 setup.py develop` and it will just use the files from that directory.

**Comment by Kaixhin** [comment]
Ah no _pymclevel_ is now installed, and I'm trying to install _pymcworldgen_ now. It doesn't seem to have a `setup.py`, or anything for `make`, `CMake` etc.?

**Comment by alexjc** [comment]
That doesn't need installing, just extracting into the `minecraft` folder and it's good to go!

**Comment by Kaixhin** [comment]
Perfect - I'm using a `git submodule add` to get that into the folder.

I've run `python main.py` successfully to create some files in the `output` folder, but I'm having trouble working out how to get `mapcrafter.sh` to work. I've done a `git submodule add` of [this repo](https://github.com/mapcrafter/mapcrafter), used `CMake` to generate a Makefile, and then run `make` and `sudo make install` successfully. The shell script seems to expect various files in other places though...

**Comment by alexjc** [comment]
The binary doesn't work?

**Comment by alexjc** [comment]
Going to close this as i added 10.9 and 10.8 versions, we have a binary of mapcrafter also on GitHub. https://github.com/aigamedev/mapcrafter/releases

**Comment by Kaixhin** [comment]
Yep if you could just add 10.9 and 10.8 to the mapcrafter releases on GitHub that should fix the last bit of the installation :+1:

FYI the error I got when adjusting `mapcrafter.sh` to use (my now globally installed binary) should be sorted with the nuclai installer putting a mapcrafter folder in the minecraft folder (judging by the exports of LD_LIBRARY_PATH and DYLD_LIBRARY_PATH):

``` sh
2015-12-21 16:19:33 [FATAL] [default] Unable to parse configuration file:
2015-12-21 16:19:33 [ERROR] [default] Configuration root section:
2015-12-21 16:19:33 [ERROR] [default]  - Error: 'template_dir' must be an existing directory! '/pmgai/minecraft/./mapcrafter/data/template' does not exist!
2015-12-21 16:19:33 [ERROR] [default] Global map section:
2015-12-21 16:19:33 [ERROR] [default]  - Error: 'texture_dir' must be an existing directory! '/pmgai/minecraft/./mapcrafter/data/textures' does not exist!
```
